// Emoji shortcode table — Mattermost/gemoji naming, curated to the ~370 codes
// that cover the overwhelming majority of real chat usage. Unknown codes render
// as literal text, so an incomplete table degrades gracefully; extend freely.
export const EMOJI = {
  // smileys
  smile: "😄", smiley: "😃", grin: "😁", grinning: "😀", laughing: "😆",
  satisfied: "😆", joy: "😂", rofl: "🤣", slightly_smiling_face: "🙂",
  upside_down_face: "🙃", wink: "😉", blush: "😊", innocent: "😇",
  heart_eyes: "😍", smiling_face_with_three_hearts: "🥰", kissing_heart: "😘",
  star_struck: "🤩", yum: "😋", stuck_out_tongue: "😛",
  stuck_out_tongue_winking_eye: "😜", stuck_out_tongue_closed_eyes: "😝",
  zany_face: "🤪", money_mouth_face: "🤑", hugs: "🤗", thinking: "🤔",
  zipper_mouth_face: "🤐", shushing_face: "🤫", raised_eyebrow: "🤨",
  neutral_face: "😐", expressionless: "😑", no_mouth: "😶", smirk: "😏",
  unamused: "😒", roll_eyes: "🙄", grimacing: "😬", lying_face: "🤥",
  relieved: "😌", pensive: "😔", sleepy: "😪", drooling_face: "🤤",
  sleeping: "😴", mask: "😷", face_with_thermometer: "🤒",
  face_with_head_bandage: "🤕", nauseated_face: "🤢", vomiting_face: "🤮",
  sneezing_face: "🤧", hot_face: "🥵", cold_face: "🥶", woozy_face: "🥴",
  dizzy_face: "😵", exploding_head: "🤯", cowboy_hat_face: "🤠",
  partying_face: "🥳", sunglasses: "😎", nerd_face: "🤓", monocle_face: "🧐",
  confused: "😕", worried: "😟", slightly_frowning_face: "🙁", frowning_face: "☹️",
  open_mouth: "😮", hushed: "😯", astonished: "😲", flushed: "😳",
  pleading_face: "🥺", frowning: "😦", anguished: "😧", fearful: "😨",
  cold_sweat: "😰", disappointed_relieved: "😥", cry: "😢", sob: "😭",
  scream: "😱", confounded: "😖", persevere: "😣", disappointed: "😞",
  sweat: "😓", weary: "😩", tired_face: "😫", yawning_face: "🥱",
  triumph: "😤", rage: "😡", pout: "😡", angry: "😠", cursing_face: "🤬",
  smiling_imp: "😈", imp: "👿", skull: "💀", skull_and_crossbones: "☠️",
  hankey: "💩", poop: "💩", shit: "💩", clown_face: "🤡", ghost: "👻",
  alien: "👽", robot: "🤖", smiley_cat: "😺", smile_cat: "😸", joy_cat: "😹",
  heart_eyes_cat: "😻", smirk_cat: "😼", scream_cat: "🙀", crying_cat_face: "😿",
  see_no_evil: "🙈", hear_no_evil: "🙉", speak_no_evil: "🙊",
  // gestures & people
  wave: "👋", raised_back_of_hand: "🤚", raised_hand: "✋", vulcan_salute: "🖖",
  ok_hand: "👌", pinched_fingers: "🤌", v: "✌️", crossed_fingers: "🤞",
  love_you_gesture: "🤟", metal: "🤘", call_me_hand: "🤙", point_left: "👈",
  point_right: "👉", point_up_2: "👆", point_down: "👇", point_up: "☝️",
  "+1": "👍", thumbsup: "👍", "-1": "👎", thumbsdown: "👎", fist: "✊",
  facepunch: "👊", punch: "👊", clap: "👏", raised_hands: "🙌",
  open_hands: "👐", palms_up_together: "🤲", handshake: "🤝", pray: "🙏",
  writing_hand: "✍️", nail_care: "💅", selfie: "🤳", muscle: "💪",
  eyes: "👀", eye: "👁️", brain: "🧠", tongue: "👅", lips: "👄", ear: "👂",
  nose: "👃", baby: "👶", child: "🧒", boy: "👦", girl: "👧", adult: "🧑",
  man: "👨", woman: "👩", older_man: "👴", older_woman: "👵",
  police_officer: "👮", detective: "🕵️", guard: "💂", construction_worker: "👷",
  prince: "🤴", princess: "👸", santa: "🎅", angel: "👼", superhero: "🦸",
  mage: "🧙", ninja: "🥷", walking: "🚶", runner: "🏃", running: "🏃",
  dancer: "💃", man_dancing: "🕺", people_hugging: "🫂", couple: "👫",
  shrug: "🤷", facepalm: "🤦", bow: "🙇", raising_hand: "🙋",
  // hearts & symbols
  heart: "❤️", orange_heart: "🧡", yellow_heart: "💛", green_heart: "💚",
  blue_heart: "💙", purple_heart: "💜", black_heart: "🖤", white_heart: "🤍",
  brown_heart: "🤎", broken_heart: "💔", heavy_heart_exclamation: "❣️",
  two_hearts: "💕", sparkling_heart: "💖", heartpulse: "💗", heartbeat: "💓",
  revolving_hearts: "💞", cupid: "💘", gift_heart: "💝", 100: "💯",
  anger: "💢", boom: "💥", collision: "💥", dizzy: "💫", sweat_drops: "💦",
  dash: "💨", fire: "🔥", star: "⭐", star2: "🌟", sparkles: "✨", zap: "⚡",
  // nature & weather
  sunny: "☀️", partly_sunny: "⛅", cloud: "☁️", rain_cloud: "🌧️",
  thunder_cloud_and_rain: "⛈️", rainbow: "🌈", umbrella: "☔",
  snowflake: "❄️", snowman: "⛄", comet: "☄️", droplet: "💧", ocean: "🌊",
  crescent_moon: "🌙", full_moon: "🌕", new_moon: "🌑", sun_with_face: "🌞",
  earth_africa: "🌍", earth_americas: "🌎", earth_asia: "🌏",
  globe_with_meridians: "🌐", seedling: "🌱", evergreen_tree: "🌲",
  deciduous_tree: "🌳", palm_tree: "🌴", cactus: "🌵", four_leaf_clover: "🍀",
  maple_leaf: "🍁", fallen_leaf: "🍂", leaves: "🍃", mushroom: "🍄",
  rose: "🌹", wilted_flower: "🥀", sunflower: "🌻", blossom: "🌼",
  tulip: "🌷", cherry_blossom: "🌸", hibiscus: "🌺",
  // animals
  dog: "🐶", cat: "🐱", mouse: "🐭", hamster: "🐹", rabbit: "🐰",
  fox_face: "🦊", bear: "🐻", panda_face: "🐼", koala: "🐨", tiger: "🐯",
  lion: "🦁", cow: "🐮", pig: "🐷", frog: "🐸", monkey_face: "🐵",
  chicken: "🐔", penguin: "🐧", bird: "🐦", baby_chick: "🐤", duck: "🦆",
  eagle: "🦅", owl: "🦉", bat: "🦇", wolf: "🐺", boar: "🐗", horse: "🐴",
  unicorn: "🦄", bee: "🐝", bug: "🐛", butterfly: "🦋", snail: "🐌",
  lady_beetle: "🐞", ant: "🐜", spider: "🕷️", scorpion: "🦂", turtle: "🐢",
  snake: "🐍", lizard: "🦎", "t-rex": "🦖", sauropod: "🦕", octopus: "🐙",
  squid: "🦑", shrimp: "🦐", lobster: "🦞", crab: "🦀", blowfish: "🐡",
  tropical_fish: "🐠", fish: "🐟", dolphin: "🐬", flipper: "🐬",
  whale: "🐳", shark: "🦈", crocodile: "🐊",
  // food & drink
  apple: "🍎", green_apple: "🍏", pear: "🍐", tangerine: "🍊", orange: "🍊",
  lemon: "🍋", banana: "🍌", watermelon: "🍉", grapes: "🍇", strawberry: "🍓",
  melon: "🍈", cherries: "🍒", peach: "🍑", mango: "🥭", pineapple: "🍍",
  coconut: "🥥", kiwi_fruit: "🥝", tomato: "🍅", eggplant: "🍆",
  avocado: "🥑", broccoli: "🥦", corn: "🌽", hot_pepper: "🌶️",
  cucumber: "🥒", carrot: "🥕", potato: "🥔", croissant: "🥐", bread: "🍞",
  baguette_bread: "🥖", pretzel: "🥨", cheese: "🧀", egg: "🥚",
  fried_egg: "🍳", bacon: "🥓", pancakes: "🥞", waffle: "🧇",
  cut_of_meat: "🥩", poultry_leg: "🍗", meat_on_bone: "🍖", hotdog: "🌭",
  hamburger: "🍔", fries: "🍟", pizza: "🍕", sandwich: "🥪", taco: "🌮",
  burrito: "🌯", falafel: "🧆", ramen: "🍜", spaghetti: "🍝", curry: "🍛",
  sushi: "🍣", bento: "🍱", dumpling: "🥟", rice: "🍚", rice_ball: "🍙",
  fortune_cookie: "🥠", icecream: "🍦", shaved_ice: "🍧", ice_cream: "🍨",
  doughnut: "🍩", cookie: "🍪", birthday: "🎂", cake: "🍰", cupcake: "🧁",
  pie: "🥧", chocolate_bar: "🍫", candy: "🍬", lollipop: "🍭",
  honey_pot: "🍯", coffee: "☕", tea: "🍵", milk_glass: "🥛", beer: "🍺",
  beers: "🍻", clinking_glasses: "🥂", wine_glass: "🍷", tumbler_glass: "🥃",
  cocktail: "🍸", tropical_drink: "🍹", champagne: "🍾", sake: "🍶",
  cup_with_straw: "🥤", bubble_tea: "🧋", ice_cube: "🧊",
  // activities & objects
  tada: "🎉", confetti_ball: "🎊", balloon: "🎈", gift: "🎁", trophy: "🏆",
  medal_sports: "🏅", first_place_medal: "🥇", second_place_medal: "🥈",
  third_place_medal: "🥉", soccer: "⚽", basketball: "🏀", football: "🏈",
  baseball: "⚾", tennis: "🎾", volleyball: "🏐", "8ball": "🎱", dart: "🎯",
  game_die: "🎲", video_game: "🎮", jigsaw: "🧩", chess_pawn: "♟️",
  performing_arts: "🎭", art: "🎨", microphone: "🎤", headphones: "🎧",
  musical_note: "🎵", notes: "🎶", guitar: "🎸", violin: "🎻", drum: "🥁",
  trumpet: "🎺", saxophone: "🎷", musical_keyboard: "🎹", clapper: "🎬",
  movie_camera: "🎥", camera: "📷", video_camera: "📹", tv: "📺",
  radio: "📻", iphone: "📱", computer: "💻", desktop_computer: "🖥️",
  keyboard: "⌨️", printer: "🖨️", telephone: "☎️", phone: "☎️",
  battery: "🔋", electric_plug: "🔌", bulb: "💡", flashlight: "🔦",
  candle: "🕯️", wastebasket: "🗑️", moneybag: "💰", dollar: "💵",
  euro: "💶", credit_card: "💳", gem: "💎", balance_scale: "⚖️",
  wrench: "🔧", hammer: "🔨", hammer_and_wrench: "🛠️", nut_and_bolt: "🔩",
  gear: "⚙️", bomb: "💣", hocho: "🔪", shield: "🛡️", crystal_ball: "🔮",
  telescope: "🔭", microscope: "🔬", pill: "💊", syringe: "💉", dna: "🧬",
  microbe: "🦠", test_tube: "🧪", thermometer: "🌡️", broom: "🧹",
  soap: "🧼", sponge: "🧽", fire_extinguisher: "🧯", shopping_cart: "🛒",
  key: "🔑", door: "🚪", chair: "🪑", bed: "🛏️", couch_and_lamp: "🛋️",
  teddy_bear: "🧸", framed_picture: "🖼️", shopping: "🛍️", luggage: "🧳",
  hourglass: "⌛", hourglass_flowing_sand: "⏳", watch: "⌚",
  alarm_clock: "⏰", stopwatch: "⏱️", calendar: "📆", date: "📅",
  memo: "📝", pencil: "📝", pencil2: "✏️", pen: "🖊️", paintbrush: "🖌️",
  crayon: "🖍️", briefcase: "💼", file_folder: "📁", open_file_folder: "📂",
  clipboard: "📋", pushpin: "📌", round_pushpin: "📍", paperclip: "📎",
  straight_ruler: "📏", triangular_ruler: "📐", scissors: "✂️",
  lock: "🔒", unlock: "🔓", closed_lock_with_key: "🔐", book: "📖",
  open_book: "📖", books: "📚", notebook: "📓", page_with_curl: "📃",
  scroll: "📜", page_facing_up: "📄", newspaper: "📰", bookmark: "🔖",
  label: "🏷️", envelope: "✉️", email: "📧", "e-mail": "📧",
  incoming_envelope: "📨", outbox_tray: "📤", inbox_tray: "📥",
  package: "📦", mailbox: "📫", postbox: "📮",
  chart_with_upwards_trend: "📈", chart_with_downwards_trend: "📉",
  bar_chart: "📊", mag: "🔍", mag_right: "🔎",
  // travel
  rocket: "🚀", airplane: "✈️", car: "🚗", red_car: "🚗", taxi: "🚕",
  bus: "🚌", fire_engine: "🚒", ambulance: "🚑", police_car: "🚓",
  bike: "🚲", motorcycle: "🏍️", train2: "🚆", metro: "🚇", ship: "🚢",
  sailboat: "⛵", anchor: "⚓", construction: "🚧", fuelpump: "⛽",
  traffic_light: "🚥", vertical_traffic_light: "🚦", world_map: "🗺️",
  house: "🏠", office: "🏢", hospital: "🏥", bank: "🏦", hotel: "🏨",
  school: "🏫", factory: "🏭", castle: "🏰", tent: "⛺",
  mount_fuji: "🗻", volcano: "🌋", desert_island: "🏝️", beach_umbrella: "🏖️",
  // symbols
  warning: "⚠️", no_entry: "⛔", no_entry_sign: "🚫",
  white_check_mark: "✅", ballot_box_with_check: "☑️",
  heavy_check_mark: "✔️", x: "❌", negative_squared_cross_mark: "❎",
  question: "❓", exclamation: "❗", bangbang: "‼️", interrobang: "⁉️",
  heavy_plus_sign: "➕", heavy_minus_sign: "➖", heavy_division_sign: "➗",
  infinity: "♾️", recycle: "♻️", wheelchair: "♿", vs: "🆚", new: "🆕",
  free: "🆓", ok: "🆗", cool: "🆒", sos: "🆘", up: "🆙", id: "🆔",
  information_source: "ℹ️", red_circle: "🔴", orange_circle: "🟠",
  yellow_circle: "🟡", green_circle: "🟢", blue_circle: "🔵",
  purple_circle: "🟣", black_circle: "⚫", white_circle: "⚪",
  red_square: "🟥", green_square: "🟩", blue_square: "🟦",
  checkered_flag: "🏁", triangular_flag_on_post: "🚩", white_flag: "🏳️",
  black_flag: "🏴", rainbow_flag: "🏳️‍🌈", arrow_right: "➡️",
  arrow_left: "⬅️", arrow_up: "⬆️", arrow_down: "⬇️",
  left_right_arrow: "↔️", arrow_up_down: "↕️", arrows_counterclockwise: "🔄",
  repeat: "🔁", fast_forward: "⏩", rewind: "⏪", arrow_forward: "▶️",
  arrow_backward: "◀️", pause_button: "⏸️", stop_button: "⏹️",
  mute: "🔇", speaker: "🔈", sound: "🔉", loud_sound: "🔊", bell: "🔔",
  no_bell: "🔕", mega: "📣", loudspeaker: "📢", speech_balloon: "💬",
  thought_balloon: "💭", clock1: "🕐", clock12: "🕛", hash: "#️⃣",
  asterisk: "*️⃣", zero: "0️⃣", one: "1️⃣", two: "2️⃣", three: "3️⃣",
  four: "4️⃣", five: "5️⃣", six: "6️⃣", seven: "7️⃣", eight: "8️⃣",
  nine: "9️⃣", keycap_ten: "🔟",
  // a few flags
  it: "🇮🇹", us: "🇺🇸", gb: "🇬🇧", uk: "🇬🇧", de: "🇩🇪", fr: "🇫🇷",
  es: "🇪🇸", eu: "🇪🇺", jp: "🇯🇵", cn: "🇨🇳", br: "🇧🇷", in: "🇮🇳",
  ca: "🇨🇦", au: "🇦🇺", ch: "🇨🇭", nl: "🇳🇱", pt: "🇵🇹", se: "🇸🇪",
};
